auth_enabled: false
server:
    http_listen_port: 3100
    grpc_listen_port: 9096

common:
    path_prefix: /tmp/loki
    replication_factor: 1
    ring:
        kvstore:
            store: inmemory

storage_config:
    tsdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_location: /tmp/loki/index_cache
    filesystem:
        directory: /tmp/loki/chunks

ingester:
    chunk_encoding: snappy
    lifecycler:
        ring:
            kvstore:
                store: inmemory
            replication_factor: 1

schema_config:
    configs:
        - from: 2025-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
              prefix: index_
              period: 24h
