target: all,alertmanager
common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/mimir
server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: warn
distributor:
  ring:
    kvstore:
      store: inmemory
ingester:
  ring:
    kvstore:
      store: inmemory
