target: all,alertmanager

multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/block
  tsdb:
    dir: /data/mimir/tsdb

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/rules

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/mimir

server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: warn

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
