server:
  http_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: grpc://loki:9096/loki/api/v1/push
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
