server:
  http_listen_port: 3200
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095
  log_level: info
  log_format: logfmt

distributor:
  receivers:
    otlp:
      protocols:
        http: # 4318
          endpoint: 0.0.0.0:4318
        grpc: # 4317
          endpoint: 0.0.0.0:4317

ingester:
  lifecycler:
    ring:
      replication_factor: 1

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/traces

metrics_generator:
  storage:
    path: /tmp/tempo/storage
  traces_storage:
    path: /tmp/tempo/traces_storage
  processor:
    span_metrics:
    service_graphs:
    local_blocks:
      flush_to_storage: true
      filter_server_spans: false
