version: "2"
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - revive
    - staticcheck
  settings:
    revive:
      max-open-files: 2048
      severity: error
      enable-all-rules: true
      rules:
        - name: line-length-limit
          arguments: [90]
        - name: package-comments
          disabled: true
      directives:
        - name: specify-disable-reason
          severity: error
