name: Lint

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.0
          only-new-issues: true
          args: ./...

  pwa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: |
            cwd: app
            args: [--frozen-lockfile]
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      - name: Type check
        run: pnpm exec tsc --noEmit
        working-directory: app
      - name: ESLint
        run: pnpm exec eslint src --ext ts,tsx
        working-directory: app
